In [1]:
import numpy as np

In [ ]:
#understanding the identity matrix :-[all the ones should be in diagonal]


In [2]:
array_eye=np.eye(5)

In [3]:
array_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#does the numpy accepts the float data types

#array of floats..!

In [6]:
array_of_floats=np.arange(0,2,0.3)

In [7]:
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
#how to create a two dimensional array

In [8]:
array_2d=np.array([(2,4,6),(3,5,7)])

In [9]:
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [ ]:
#how to validate the shape of a matrix:-
-------------------------------------

#by useing shape method we can validate matrix shape

In [10]:
array_2d.shape

(2, 3)

In [ ]:
#Generate randno matrix 

In [12]:
x=np.arange(6)

In [13]:
x   #this is a liear matrix i.e---> one dimensioanl array

array([0, 1, 2, 3, 4, 5])

In [14]:
x.shape

(6,)

In [ ]:
req:- changing the above linear matrix to 2-dim matrix
----

In [17]:
array_nd=x.reshape(2,3)

In [27]:
array_reshape=np.arange(10).reshape(5,2)

In [28]:
array_reshape

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
printing arrays:-
--------------

In [ ]:
1D array:-
-------

In [29]:
a=np.arange(8)

In [30]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [31]:
a.shape  #linear shape

(8,)

In [ ]:
2D array:-
--------

In [34]:
b=np.arange(16).reshape(4,4)

In [35]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
b.shape      #2 dimensional

(4, 4)

In [ ]:
3D arrays:-
----------

In [42]:
c=np.arange(24).reshape(2,3,4)

In [43]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [44]:
c.shape

(2, 3, 4)