In [3]:
import numpy as np

In [ ]:
#Arithimatic operations on matrixs:-
----------------------------------

In [5]:
a=np.array([10,10,10])
b=np.array([5,5,5])

In [9]:
print(a)
print(b)

[10 10 10]
[5 5 5]


In [10]:
#addition of matrixs

a+b

array([15, 15, 15])

In [11]:
#subtraction of matrix

a-b

array([5, 5, 5])

In [22]:
#division of matrix

print(a/b)

[2. 2. 2.]


In [23]:
#modulo division

a%3

array([1, 1, 1], dtype=int32)

In [ ]:
#comparison operators

>,<,==

In [24]:
a<35

array([ True,  True,  True])

In [25]:
a>35

array([False, False, False])

In [26]:
b==5

array([ True,  True,  True])

In [27]:
#squaring operation


a**2

array([100, 100, 100], dtype=int32)

In [28]:
a**3

array([1000, 1000, 1000], dtype=int32)

In [ ]:
#Modifying an existing array rather that creating a new one:-
-----------------------------------------------------------

In [ ]:
req:- To modify a values into 30
----

In [29]:
a*=3

In [30]:
a

array([30, 30, 30])

In [ ]:
req:- To modify b value into 35
---

In [31]:
b += a

In [32]:
b

array([35, 35, 35])

In [ ]:
#UNARY OPERATORS:-
-----------------

sum()
max()
min()

In [33]:
ages=np.array([12,15,17,22,26,30])

In [34]:
ages

array([12, 15, 17, 22, 26, 30])

In [36]:
#getting sum of the ages matrix

ages.sum()

122

In [37]:
#getting max value in ages

ages.max()

30

In [38]:
#getting min value from ages matrix

ages.min()

12

In [41]:
numbers=np.arange(12).reshape(3,4)

In [42]:
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
NOTE:-
******

In a 2D array AXIS 0 ------> cloumns
In a 2D array AXIS 1 ------> rows

In [48]:
#getting columns sum:-
                                #colmuns sum

numbers.sum(axis=0)

array([12, 15, 18, 21])

In [47]:
#getting rows sum:-
                                #rows sum
    
numbers.sum(axis=1)

array([ 6, 22, 38])