In [ ]:
Intro:- numpy is an 3rd party library of python ,basically handles all the numarical computations
----

numpy will be acting as a base layer ----> under which we will be able perform all mathametical oprations

In [ ]:
understanding the datatypes of numpy:-
------------------------------------

ndarray   ------> n dimensional array

array and a noraml python list ------>

we can import it as ----> import numpy as np


why we write numpy as np  (we need to fllow the python community)

we can give any name in the in the universe instead of np

In [4]:
import numpy as np

In [5]:
array_one=np.array([1,2,3])

In [6]:
array_one

array([1, 2, 3])

In [8]:
type(array_one)

numpy.ndarray

In [9]:
numbers=[4,5,6,7]

In [10]:
array_two=np.array(numbers)

In [11]:
array_two

array([4, 5, 6, 7])

In [12]:
type(array_two)

numpy.ndarray

In [ ]:
#how to print a null matrix:-
---------------------------

In [17]:
array_of_zeros=np.zeros((3,4))     


# 3 for rows
# 4 for columns

In [18]:
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#how to print a array with ones

In [28]:
array_of_ones=np.ones((4,5))

# 4 for rows
# 5 for columns

In [29]:
array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
when we are working with array ,it always gives float

In [21]:
array_of_ones_int=np.ones((4,5),dtype=np.int16)

In [22]:
array_of_ones_int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [ ]:
# what is int16


#to represent data in int values we use the method like int16

#like we have 3 types:-
---------------------   int16
                        int32
                        int64
        
#based size of the data we use the above int16,int32 and int64

#if array size and data is small data we use int16 ----> like that

In [ ]:
#how to print identity matrix:-
------------------------------
    

In [38]:
array_eye=np.eye(4)

In [39]:
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
array_eye_int=np.eye(4,dtype=np.int16)

In [41]:
array_eye_int

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

In [ ]:
req:- Using nmpy I want to have a even numbers printed
----


for this we areusing method called arrage()

In [ ]:
normal python ------> range function

numpy --------------> arrange method

In [43]:
array_of_evens=np.arange(2,31,2)

In [44]:
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [45]:
array_of_odds=np.arange(1,31,2)

In [46]:
array_of_odds

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])